# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dbserver.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import user_pb2 as user__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x64\x62server.proto\x12\x02\x64\x62\x1a\nuser.proto\"\x10\n\x0e\x44\x65\x66\x61ultRequest\"-\n\x16GetResourceByIdRequest\x12\x13\n\x0bresource_id\x18\x01 \x01(\t\"-\n\x0fKeyValueRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"<\n\x17MultipleKeyValueRequest\x12!\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x13.db.KeyValueRequest\"1\n\x0f\x44\x65\x66\x61ultResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\r\n\x05\x65rror\x18\x02 \x01(\x08\"!\n\x0eHealthResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xa7\x02\n\tDbService\x12\x35\n\x0bHealthCheck\x12\x12.db.DefaultRequest\x1a\x12.db.HealthResponse\x12\x34\n\nCreateUser\x12\x11.db.CreateUserReq\x1a\x11.db.CreateUserRes\"\x00\x12\x34\n\nUpdateUser\x12\x11.db.UpdateUserReq\x1a\x11.db.UpdateUserRes\"\x00\x12=\n\rGetPagedUsers\x12\x14.db.GetPagedUsersReq\x1a\x14.db.GetPagedUsersRes\"\x00\x12\x38\n\x0eGetUserByField\x12\x11.db.GetByfieldReq\x1a\x11.db.GetByfieldRes\"\x00\x42\x31Z/github.com/AppsLab-KE/backend-everyshillings/dbb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dbserver_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z/github.com/AppsLab-KE/backend-everyshillings/db'
  _DEFAULTREQUEST._serialized_start=34
  _DEFAULTREQUEST._serialized_end=50
  _GETRESOURCEBYIDREQUEST._serialized_start=52
  _GETRESOURCEBYIDREQUEST._serialized_end=97
  _KEYVALUEREQUEST._serialized_start=99
  _KEYVALUEREQUEST._serialized_end=144
  _MULTIPLEKEYVALUEREQUEST._serialized_start=146
  _MULTIPLEKEYVALUEREQUEST._serialized_end=206
  _DEFAULTRESPONSE._serialized_start=208
  _DEFAULTRESPONSE._serialized_end=257
  _HEALTHRESPONSE._serialized_start=259
  _HEALTHRESPONSE._serialized_end=292
  _DBSERVICE._serialized_start=295
  _DBSERVICE._serialized_end=590
# @@protoc_insertion_point(module_scope)
