# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: otp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\totp.proto\x12\x03otp\"+\n\x13\x43reateAndSendOtpReq\x12\x14\n\x0cphone_number\x18\x01 \x01(\t\"R\n\x13\x43reateAndSendOtpRes\x12\x13\n\x0bstatus_code\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x15\n\rtracking_uuid\x18\x03 \x01(\t\"7\n\x0cVerifyOTPReq\x12\x10\n\x08otp_code\x18\x01 \x01(\t\x12\x15\n\rtracking_uuid\x18\x02 \x01(\t\"4\n\x0cVerifyOTPRes\x12\x13\n\x0bstatus_code\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\"#\n\x0cResendOTPReq\x12\x13\n\x0btracking_id\x18\x01 \x01(\t\"K\n\x0cResendOTPRes\x12\x13\n\x0bstatus_code\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x15\n\rtracking_uuid\x18\x03 \x01(\tB2Z0github.com/AppsLab-KE/backend-everyshillings/otpb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'otp_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z0github.com/AppsLab-KE/backend-everyshillings/otp'
  _CREATEANDSENDOTPREQ._serialized_start=18
  _CREATEANDSENDOTPREQ._serialized_end=61
  _CREATEANDSENDOTPRES._serialized_start=63
  _CREATEANDSENDOTPRES._serialized_end=145
  _VERIFYOTPREQ._serialized_start=147
  _VERIFYOTPREQ._serialized_end=202
  _VERIFYOTPRES._serialized_start=204
  _VERIFYOTPRES._serialized_end=256
  _RESENDOTPREQ._serialized_start=258
  _RESENDOTPREQ._serialized_end=293
  _RESENDOTPRES._serialized_start=295
  _RESENDOTPRES._serialized_end=370
# @@protoc_insertion_point(module_scope)
